# XOR

- 하나의 히든 레이어를 도입한다.
- input layer는 2개의 노드 + 1개의 바이어스
- hidden layer는 3개의 노드 + 1개의 바이어스
- output은 하나의 노드로 한다.

In [1]:
import numpy as np

In [2]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

In [3]:
X = np.array([[0,0,1],[0,1,1],[1,0,1],[1,1,1]]) #세번째 항은 bias
y = np.array([[0],[1],[1],[0]])

In [4]:
inputs, hiddens, outputs = 3, 4, 1 #3x4 matrix

In [5]:
np.random.seed(1)
w= 2*np.random.random((inputs,hiddens))-1 #원래 랜덤은 0부터 1사이인데 이렇게 하면 -1과 1사이가 됨
w
omega = 2*np.random.random((hiddens,outputs))-1

In [6]:
def o(x):
    sigmoid(net_0)
    return sigmoid(net_0)

In [7]:
net_h=np.dot(X[0],w) #hidden
h=sigmoid(net_h)
h, omega

(array([0.44856632, 0.51939863, 0.45968497, 0.59156505]),
 array([[-0.5910955 ],
        [ 0.75623487],
        [-0.94522481],
        [ 0.34093502]]))

In [8]:
X[0]

array([0, 0, 1])

In [9]:
#정리

def sigmoid(x):
    return 1/(1+np.exp(-x))
np.random.seed(1)
w= 2*np.random.random((inputs,hiddens))-1 #원래 랜덤은 0부터 1사이인데 이렇게 하면 -1과 1사이가 됨
omega = 2*np.random.random((hiddens,outputs))-1
inputs, hiddens, outputs = 3, 4, 1

In [10]:
for i in range(4):
    net_h=np.dot(X[i],w)
    h=sigmoid(net_h)
    net_0=np.dot(h,omega)
    o=sigmoid(net_0)
    
    error=(o - y[i])
    print(error)

[0.47372957]
[-0.51104304]
[-0.45615914]
[0.54470837]


In [11]:
w=np.random.rand(3,4)
eta=0.1
dh=[0,0,0,0]

In [12]:
for n in range(1000):
    error_sum=0
    for i in range(4):
        h=sigmoid(net_h)
        net_0=np.dot(h,omega)
        o=sigmoid(net_0)
        
        error=error+(o - y[i])**2
        d0=(o-y[i])*sigmoid(net_0)*(1-sigmoid(net_0))
        
    for j in range(4):
        dh[j]=d0*omega[j]*sigmoid(net_0)*(1-sigmoid(net_0))
        omega[j]=omega[j]-eta*d0*h[j]
        for k in range(3):
            w[k][j]=w[k][j]-eta*dh[j]*X[i][k]


In [13]:
for i in range(4):
    net_h=np.dot(X[i],w)
    h=sigmoid(net_h)
    net_0=np.dot(h,omega)
    o=sigmoid(net_0)
    print(o)

[0.0093743]
[0.00352388]
[0.00437517]
[0.00267307]
